stages:
  download:
    cmd: python data/download.py
    outs:
    - dataset/raw
  preprocess:
    cmd: python preprocess.py
    deps:
    - dataset/raw
    outs:
    - dataset/processed
  detect:
    cmd: python detect.py
    deps:
    - dataset/processed
    outs:
    - dataset/crop_rows
