[project]
name = "roweeder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "colorlog>=6.10.1",
    "einops>=0.8.2",
    "lovely-tensors>=0.1.21",
    "opencv-python>=4.13.0.92",
    "optuna>=4.7.0",
    "ptflops>=0.7.5",
    "pyyaml>=6.0.3",
    "ruamel-yaml>=0.19.1",
    "safetensors>=0.7.0",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.8.0",
    "streamlit>=1.54.0",
    "torchmetrics>=1.8.2",
    "torchvision>=0.25.0",
    "transformers>=5.1.0",
    "wandb>=0.24.2",
]
