#!/bin/bash

#SBATCH -A IscrC_PENELOPE
#SBATCH -p boost_usr_prod
#SBATCH --qos normal
#SBATCH --time 24:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --mem=123000
#SBATCH --job-name=run_ssl
#SBATCH --out=run.out
#SBATCH --err=run.out

srun ./slurm/launch_run_exe $@