experiment:
  # It contains all the about the grids and the group of runs:
  name: RowWeed # name of the logger platform experiment
  group: ResNet50 # name of group of experiments for the logger platform
  continue_with_errors: False # continue with other runs even if a run fails
  start_from_grid: 0 # skip grids in the grid search
  start_from_run: 0 # skip runs from the selected grid
  task: classification # task to perform
  test_task: segmentation
  search: grid
  # n_trials: 5

parameters:
  # Contains the parameters to build the grid.
  # Each value should be a dict or a list
  seed: &seed [42] # random seed to set

  tracker:
    ignored_files: ["*.bin,*.safetensors"]
    train_image_log_frequency: [20]
    val_image_log_frequency: [10]
    test_image_log_frequency: [10]
    tags: [[Focal]]

  train:
    max_epochs: [5]
    compile: [False]
    initial_lr: [0.01, 0.005, 0.001, 0.0005, 0.0001]
    optimizer: [AdamW]
    # scheduler:
    #   type: [reduce_lr_on_plateau]
    #   step_moment: [epoch]
    #   patience: [0]
    watch_metric: [F1Score]
    freeze_backbone: [False]
    check_nan: [1] # check for nan every n batches

  loss:
    class_weighting: [True]
    components:
      - focal:
          weight: 1.0
          gamma: 0.0

  model:
    name: [seg-resnet50] # path to model class or model name contained in EzDL or super-gradients
    params:
      input_channels: &input_channels [['R', 'G', 'B']]
      plant_detector_params:
        name: [NDVIDetector]
        params:
          threshold: [0.1]
      slic_params:
        percent: [0.005]
        compactness: [20]
        sigma: [1]

  dataset: # parameters depending on the class you defined for the dataset
    root: [dataset/generated/69023956/patches] # path to the dataset
    test_root: [dataset/patches/512] 
    channels: *input_channels
    train_fields: [["000", "001", "002", "004"]]
    test_fields: [["003"]]
    preprocess:
      mean: [[0.485, 0.456, 0.406]]
      std: [[0.229, 0.224, 0.225]]
      resize: [[224, 224]]
    test_preprocess:
      mean: [[0.485, 0.456, 0.406]]
      std: [[0.229, 0.224, 0.225]]

  dataloader:
    num_workers: [0]
    batch_size: [16]

  train_metrics:
    F1Score: &metric_params
      task: [binary]
  val_metrics:
    F1Score: *metric_params
  test_metrics:
    JaccardIndex: &test_metric_params
      num_classes: [3]
      task: [multiclass]
      average: [macro]
    F1Score: *test_metric_params

other_grids: